/usb_camera_node:
  ros__parameters:
    # 视频流来源选择：
    # 若 use_zmq 为 True，则忽略本地相机和 web_cam，直接通过 ZMQ 接收视频流
    use_zmq: False
    zmq_endpoint: "tcp://127.0.0.1:5134"

    # 原有相机配置 (当 use_zmq 为 False 时生效)
    web_cam: True
    web_cam_url: "http://192.168.1.216:4747/video"
    camera_index: 0

    # 编码格式: "MJPG" 或 "YUYV" or "NV12" or "RGB3"
    pixel_format: "MJPG"

    # 输出编码格式 mac -> "rgb8" other -> "bgr8"
    encoding_str: "rgb8"

    # 图像尺寸
    frame_width: 640
    frame_height: 480

    # 帧率 (640x480 下 MJPG 通常能跑很高，240是合理的)
    fps: 240.0

    # 曝光
    exposure_auto: True
    exposure_time: 800

    # 增益
    gain: 128